// snippet.js — generate a self-contained Python import snippet from a parsed model.
//
// The public web edition never touches the user's NetBox. Instead it hands back a
// ready-to-run pynetbox script that the user executes themselves, against their own
// NetBox, with their own token. Credentials never leave their machine.

export function buildSnippet(model) {
  const m = model || {};
  const data = JSON.stringify(m, null, 2);
  return `#!/usr/bin/env python3
# NetBox import — generated by ENSECNET CiscoParserWeb
# Run on a host that can reach your NetBox. Requires: pip install pynetbox
#
#   NETBOX_URL=http://netbox.local:8080 NETBOX_TOKEN=xxxx python3 import.py
#
# Nothing here was sent anywhere — this script and the model below were generated
# in your browser session and run by you.

import os, pynetbox

MODEL = ${data}

NB_URL = os.environ["NETBOX_URL"]
NB_TOKEN = os.environ["NETBOX_TOKEN"]

nb = pynetbox.api(NB_URL, token=NB_TOKEN)
nb.http_session.verify = False

def ensure(endpoint, lookup, create):
    obj = endpoint.get(**lookup)
    return obj or endpoint.create(**create)

mfr  = ensure(nb.dcim.manufacturers, {"slug": "cisco"},
              {"name": "Cisco", "slug": "cisco"})
dt   = ensure(nb.dcim.device_types, {"slug": "ios-xe-generic"},
              {"manufacturer": mfr.id, "model": "IOS-XE Generic", "slug": "ios-xe-generic"})
role = ensure(nb.dcim.device_roles, {"slug": "router"},
              {"name": "Router", "slug": "router", "color": "2196f3"})
site = ensure(nb.dcim.sites, {"slug": "imported"},
              {"name": "Imported", "slug": "imported", "status": "active"})

dev = nb.dcim.devices.get(name=MODEL["name"]) or nb.dcim.devices.create(
    name=MODEL["name"], device_type=dt.id, role=role.id, site=site.id, status="active")

for v in MODEL.get("vlans", []):
    if not nb.ipam.vlans.get(vid=v["vid"], site_id=site.id):
        nb.ipam.vlans.create(vid=int(v["vid"]), name=v["name"], site=site.id, status="active")

for vrf in MODEL.get("vrfs", []):
    if not nb.ipam.vrfs.get(name=vrf["name"]):
        nb.ipam.vrfs.create(name=vrf["name"], rd=vrf.get("rd"))

for intf in MODEL.get("interfaces", []):
    iface = nb.dcim.interfaces.get(device_id=dev.id, name=intf["name"]) or \\
        nb.dcim.interfaces.create(device=dev.id, name=intf["name"], type=intf["type"],
                                  enabled=intf["enabled"], description=intf.get("description") or "")
    addr = intf.get("address")
    if addr and not nb.ipam.ip_addresses.get(address=addr):
        nb.ipam.ip_addresses.create(address=addr, status="active",
            assigned_object_type="dcim.interface", assigned_object_id=iface.id)

if MODEL.get("config_context"):
    dev.local_context_data = MODEL["config_context"]
    dev.save()

print("Imported device:", dev.name, "->", NB_URL)
`;
}
